CREATE DATABASE QLTUYENSINH
GO
USE QLTUYENSINH
GO

-- TẠO BẢNG USERS
CREATE TABLE USERS
(
	STT INT IDENTITY,
	EMAIL NVARCHAR (30) NOT NULL PRIMARY KEY,
	PASS NVARCHAR (30),
	ROLL INT NOT NULL DEFAULT 0 -- 1 : ADMIN && 0 STAFF
)
-- TẠO BẢNG BAN TUYỂN SINH 
CREATE TABLE BANTUYENSINH
(
	MA_BANTS NVARCHAR (10) NOT NULL PRIMARY KEY,
	TEN_BANTS NVARCHAR (20) 
)
-- TẠO BẢNG KHU VỰC ƯU TIÊN
CREATE TABLE KHUVUC 
(
	KHU_VUC NVARCHAR (5) NOT NULL PRIMARY KEY,
	TEN_KHU_VUC NVARCHAR(50)
)
GO
-- TẠO BẢNG TỈNH
CREATE TABLE TINH
(
	MA_TINH NVARCHAR(5) NOT NULL PRIMARY KEY,
	TEN_TINH NVARCHAR(100),
)
GO
-- TẠO BẢNG HUYỆN
CREATE TABLE HUYEN 
(
	MA_HUYEN NVARCHAR(5) NOT NULL,
	TEN_HUYEN NVARCHAR (100),
	MA_TINH NVARCHAR(5),
	PRIMARY KEY (MA_HUYEN),
	FOREIGN KEY (MA_TINH) REFERENCES TINH(MA_TINH)
)
GO

-- TẠO BẢNG TRƯỜNG PHỔ THÔNG
CREATE TABLE TRUONGPT 
(
	MA_TRUONG NVARCHAR (10) NOT NULL,
	TEN_TRUONG NVARCHAR(100),
	MA_TINH NVARCHAR(5),
	KHU_VUC NVARCHAR(5),
	MA_HUYEN NVARCHAR(5) ,
	DIA_CHI NVARCHAR(200),
	PRIMARY KEY (MA_TRUONG),
	FOREIGN KEY (MA_TINH) REFERENCES TINH (MA_TINH),
	FOREIGN KEY (MA_HUYEN) REFERENCES HUYEN(MA_HUYEN),
	FOREIGN KEY (KHU_VUC) REFERENCES  KHUVUC (KHU_VUC)
) 
GO

-- TẠO BẢNG ĐƠN VỊ DỰ THI
CREATE TABLE DONVIDUTHI
(
	MA_DONVI_DT NVARCHAR(5) NOT NULL,
	TEN_TRUONG_DT NVARCHAR(200),
	DIA_CHI NVARCHAR (250),
	SDT CHAR (12)
	PRIMARY KEY (MA_DONVI_DT)
)
GO

-- TẠO BẢNG ĐỐI TƯỢNG ƯU TIÊN
CREATE TABLE DOITUONG
(
	DOI_TUONG NVARCHAR(5) NOT NULL PRIMARY KEY,
	TEN_DOI_TUONG NVARCHAR(200)
)
GO

-- TẠO BẢNG KHỐI THI 
CREATE TABLE KHOITHI
(
	KHOI NVARCHAR (5) NOT NULL PRIMARY KEY,
	MON_THI_1 NVARCHAR(50),
	MON_THI_2 NVARCHAR(50),
	MON_THI_3 NVARCHAR(50),
	DIEM_SAN_DAIHOC NVARCHAR (5),
	DIEM_SAN_CAODANG NVARCHAR(5)
)
GO
-- TẠO BẢNG NGÀNH
CREATE TABLE NGANH
(
	MA_NGANH NVARCHAR(5) NOT NULL PRIMARY KEY,
	TEN_NGANH NVARCHAR(50),
	KHOI NVARCHAR (5),
	DIEM_CHUAN NVARCHAR(5),
)
GO
-- TẠO BẢNG THÍ SINH 
CREATE TABLE THISINH
(
	STT INT IDENTITY NOT NULL,
	MA_BANTS NVARCHAR (10),
-- INFO--------------------------------------
	SO_BAODANH NUMERIC (18,0) NOT NULL PRIMARY KEY,
	HO NVARCHAR(50),
	TEN NVARCHAR(50),
	GIOI_TINH NVARCHAR (10),
	NGAY_SINH NVARCHAR (10),
	DAN_TOC NVARCHAR (5),
	EMAIL NVARCHAR (50),
	SDT CHAR(12),
	MA_TRUONG NVARCHAR(10),
	MA_TINH NVARCHAR(5),
	MA_HUYEN NVARCHAR (5),
	MA_DONVI_DT NVARCHAR(5) NOT NULL,
	NAM_TOT_NGHIEP NVARCHAR (5),
	LOP_10 NVARCHAR(30),
	LOP_11 NVARCHAR(30),
	LOP_12 NVARCHAR(30),
-----------------------------------------	
---- XET TUYEN---------------------------
	KHOI NVARCHAR(5) NOT NULL,
	MA_NGANH NVARCHAR(5),
	TEN_NGANH VARCHAR (200),
	DOI_TUONG  NVARCHAR(5) NOT NULL, 
	DIEM_MON_1 NVARCHAR(4),
	DIEM_MOM_2 NVARCHAR(4),
	DIEM_MON_3 NVARCHAR(4),
	DIEM_TONG_CONG NVARCHAR(4),
	DIEM_LAM_TRON NVARCHAR (4),
	KHU_VUC NVARCHAR (5),
	DOT_XET NVARCHAR(5),
	NGUYEN_VONG NVARCHAR(5),
	DIEM_UU_TIEN NVARCHAR(5),
	TRUNG_TUYEN NVARCHAR(5),
	DIEM_CHUAN NVARCHAR (5),
	FOREIGN KEY (MA_TRUONG) REFERENCES TRUONGPT(MA_TRUONG),
	FOREIGN KEY (MA_DONVI_DT) REFERENCES DONVIDUTHI (MA_DONVI_DT),
	FOREIGN KEY (MA_TINH) REFERENCES TINH (MA_TINH),
	FOREIGN KEY (MA_HUYEN) REFERENCES HUYEN (MA_HUYEN),
	FOREIGN KEY (DOI_TUONG) REFERENCES DOITUONG (DOI_TUONG),
	FOREIGN KEY (KHU_VUC) REFERENCES KHUVUC (KHU_VUC),
	FOREIGN KEY (KHOI) REFERENCES KHOITHI (KHOI),
	FOREIGN KEY (MA_NGANH) REFERENCES NGANH (MA_NGANH),
	FOREIGN KEY (MA_TINH) REFERENCES  TINH (MA_TINH), 
	FOREIGN KEY (MA_BANTS) REFERENCES BANTUYENSINH (MA_BANTS)
)
GO

INSERT INTO USERS VALUES ( N'lehoangg1703@gmaill.com', N'123', 1)
INSERT INTO USERS VALUES ( N'minhthu@gmaill.com', N'123', 0)

select* from USERS